version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - dpobel
  ignore:
  - dependency-name: metalsmith-renamer
    versions:
    - "> 0.5.25, < 0.6"
  - dependency-name: highlight.js
    versions:
    - 10.7.0
  - dependency-name: open
    versions:
    - 8.0.0
    - 8.0.1
