language: node_js
branches:
    only:
        - master
cache:
    directories:
        - web/images

before_script:
    - cp -r `find web/images -mindepth 1 -type d` src/images/

script:
    - npm test
    - npm run build

addons:
    apt_packages:
        - graphicsmagick
