language: node_js
branches:
    only:
        - master

cache:
    directories:
        - web/images

#before_script:
#    - cp -r `find web/images -mindepth 1 -type d` src/images/

script:
    - npm test
    - npm run build

after_success:
    - npm run deploy

addons:
    apt_packages:
        - graphicsmagick

before_install:
    - openssl aes-256-cbc -K $encrypted_71d3c97bf145_key -iv $encrypted_71d3c97bf145_iv -in ssh/id_dsa.enc -out ssh/id_dsa -d
    - chmod 600 ssh/id_dsa
