language: node_js
branches:
    only:
        - master

cache:
    directories:
        - web/images

before_script:
    - npm run restorecache
    - export ASSET_REV=`git log --pretty=%h -1 assets`

script:
    - npm test
    - npm run build

after_success:
    - npm run deploy

addons:
    apt_packages:
        - graphicsmagick
        - fonts-liberation

before_install:
    - openssl aes-256-cbc -K $encrypted_71d3c97bf145_key -iv $encrypted_71d3c97bf145_iv -in ssh/id_dsa.enc -out ssh/id_dsa -d
    - chmod 600 ssh/id_dsa
env:
    global:
        secure: aKYf8fUjhOyTXY/26CHcnCES3QZK6tal5VoFfQCFt+xPgO0R2GFxMSJiYHes9erfwaIiFLVsi7Zq8VJGJc3ZkFWtfSrC1HdchUSufxxIdPvYIUghidD8wmJ/JecTMxw/wMfQNekQwouppvzEgWn4hY+k7ucMB3OGiRL8VwMow+o=
