name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Installing xmllint and pdftohtml
        if: ${{ github.ref_name != 'main' }}
        run: |
          sudo apt -y update
          sudo apt -y install libxml2-utils poppler-utils

      - name: Test
        run: npm test

      - uses: actions/cache@v4
        with:
          path: damien.pobel.fr/web/images
          key: "dp-images-2025-07-16-update-sharp"

      - name: Restore cache
        run: npm run dp:restorecache

      - name: Defining ASSET_REV
        run: echo ASSET_REV=`git log --pretty=%h -1 damien.pobel.fr/assets` >> $GITHUB_ENV

      - name: Build
        run: npm run dp:build

      - name: Deploy
        run: npm run dp:deploy
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
